---
- name: Install git
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - git
  when: mode == 'dev'

- name: Add system group
  group: name="{{ system_user }}"

- name: Add system user
  user: name="{{ system_user }}" group="{{ system_group }}" home="/home/{{ system_user }}"

- name: Ensure .ssh directory exists
  file: path="/home/{{ system_user }}/.ssh" state=directory mode=0700 owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == 'dev'

- name: Copy aws deploy key
  action: copy src="../../keys/{{ magento_deploy_key }}" dest="/home/{{ system_user }}/.ssh/{{ prefix }}" owner="{{ system_user }}" group="{{ system_group }}" mode=0600
  when: mode == 'dev'

- name: Create installation folder (web_root)
  file: path="{{ web_root }}" owner="{{ system_user }}" group="{{ system_group }}" state=directory recurse=yes mode='u=rwX,g=rwX,o=rX'

- name: Ensure .ssh/config exists
  file: path="/home/{{ system_user }}/.ssh/config" state=touch mode=0500 owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == 'dev'

- name: User ssh config template
  template: src=home_ssh_config.j2 dest="/home/{{ system_user }}/.ssh/config" owner="{{ system_user }}" group="{{ system_group }}" mode=0500
  when: mode == 'dev'

- name: gitconfig template
  template: src=gitconfig.j2 dest="/home/{{ system_user }}/.gitconfig" owner="{{ system_user }}" group="{{ system_user }}"
  when: mode == 'dev'

- name: git checkout repository for site
  git: repo="github-{{ domain }}:{{ gitrepo }}"
       dest="{{ web_root }}"
       ssh_opts="-o StrictHostKeyChecking=no -vvvv"
       accept_hostkey=True
       force=True
       key_file="/home/{{ system_user }}/.ssh/{{ prefix }}"
  sudo: yes
  sudo_user: "{{ system_user }}"
  when: mode == 'dev'

- name: Copy local.xml
  template: src=local.xml.j2 dest="{{ web_root }}/app/etc/local.xml" owner="{{ system_user }}" group="{{ system_group }}"

- name: Copy post_receive.php as github post receive webhook
  template: src=post_receive.php.j2 dest="{{ web_root }}/post_receive.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev"

- name: Copy Git.php script. Required for git-status.php and git-commit.php
  copy: src="Git.php" dest="{{ web_root }}/Git.php" owner="{{ system_user }}" group="{{ system_group }}" 
  when: mode == 'dev'

- name: Generate git-status.php for server-side git status check 
  template: src=git-status.php.j2 dest="{{ web_root }}/git-status.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev"

- name: Generate git-commit.php for server-side git commit of modified files
  template: src=git-commit.php.j2 dest="{{ web_root }}/git-commit.php" owner="{{ system_user }}" group="{{ system_group }}"
  when: mode == "dev"

#- name: Ensure cache(s) writable
#  file: dest="{{ item }}" state=directory mode=0775 recurse=yes owner="{{ system_user }}" group="{{ system_group }}"
#  with_items:
#    - "{{ web_root }}/cache/cachefs"
#    - "{{ web_root }}/cache/smarty/cache"

- name: Copy site robots.txt
  copy: src="robots.txt" dest="{{ web_root }}/robots.txt" owner="{{ system_user }}" group="{{ system_group }}"
  tags:
    - robotstxt

- name: Add Disallow / for dev sites
  lineinfile: "dest={{ web_root }}/robots.txt regexp='^Disallow: /$' line='Disallow: /' insertafter='^User-agent'"
  when: mode == "dev"
  tags:
    - robotstxt

- name: Magento cron script
  cron:
    name: "Magento cron for {{ domain }}"
    job: "/bin/sh /srv/{{ domain }}/cron.sh"
  become_user: "{{ system_user }}"
