---
- name: Install pip
  apt: name=python-pip state=latest update_cache=true

- name: Install awscli
  pip: name=awscli state=latest

- name: Create .aws directory
  file:
    dest: "/home/{{ system_user }}/.aws"
    state: directory
  become_user: "{{ system_user }}"
  when: aws_s3_access_key is defined

- name: Copy awscli configuration
  template:
    src: config.j2
    dest: "/home/{{ system_user }}/.aws/config"
    mode: 0600
  become_user: "{{ system_user }}"
  when: aws_s3_access_key is defined

- cron:
    name: "S3 Sync: {{ item.bucket }}/{{ item.folder }} sync on reboot"
    special_time: reboot
    job: "/usr/local/bin/aws s3 sync s3://{{ item.bucket }}/{{ item.folder }} /srv/{{ domain }}/{{ item.folder }}/ > /dev/null && chown -R {{ system_user }}.{{ system_group }} /srv/{{ domain }}/{{ item.folder }}/ > /dev/null"
  become_user: "{{ system_user }}"
  with_items: s3_folders

- cron:
    name: "S3 Sync: {{ item.folder }} sync"
    minute: "{{ item.interval }}"
    job: "pgrep awscli > /dev/null || /usr/local/bin/aws s3 sync /srv/{{ domain }}/{{ item.folder }}/ s3://{{ item.bucket }}/{{ item.folder }} --acl public-read > /dev/null"
  become_user: "{{ system_user }}"
  with_items: s3_folders
